#!/bin/bash

_icon_path=""
while IFS= read -r -d '' _icon_path; do
  mv $_icon_path $(dirname $_icon_path)/com.fcitx_im.$(basename $_icon_path)
done < <(find /app/share/icons/hicolor -type f -and \( -name 'fcitx.png' -or -name 'fcitx.svg' \) -print0)

_icon_path=""
while IFS= read -r -d '' _icon_path; do
  mv $_icon_path $(dirname $_icon_path)/com.fcitx_im.fcitx.$(basename $_icon_path)
done < <(find /app/share/icons/hicolor -type f -and -name 'fcitx-*' -print0)
