#!/bin/bash

flatpak run \
  --filesystem=$PWD \
  --command=flatpak-pip-generator \
  io.github.flatpak.flatpak-builder-tools \
  --requirements-file=breezy-requirements.txt \
  --output breezy-python-dependencies
