#!/bin/bash

# chrome's process singleton
export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID

flextop-init

if [[ -f $XDG_CONFIG_HOME/chrome-flags.conf ]]; then
   CHROME_USER_FLAGS="$(cat ${XDG_CONFIG_HOME}/chrome-flags.conf | egrep -v -e '^#' -e '^$')"
fi

# TODO: switch back to executing the wrapper and drop the wrapper code from here
#       this still doesn't seem to work correctly with zypak beta4
# needed before running zypak-wrapper?
#export CHROME_WRAPPER=/app/extra/google-chrome-unstable

###############################################################################
# from google's official wrapper
###############################################################################

HERE=/app/extra

## this seems mainly for the packaged xdg-mime & xdg-settings
##  and these not included in the flatpak runtime
if ! which xdg-settings &> /dev/null; then
  # Old xdg utilities. Prepend $HERE to $PATH to use ours instead.
  export PATH="$HERE:$PATH"
else
  # Use system xdg utilities. But first create mimeapps.list if it doesn't
  # exist; some systems have bugs in xdg-mime that make it fail without it.
  xdg_app_dir="${XDG_DATA_HOME:-$HOME/.local/share/applications}"
  mkdir -p "$xdg_app_dir"
  [ -f "$xdg_app_dir/mimeapps.list" ] || touch "$xdg_app_dir/mimeapps.list"
fi

# Always use our versions of ffmpeg libs.
# This also makes RPMs find the compatibly-named library symlinks.
if [[ -n "$LD_LIBRARY_PATH" ]]; then
  LD_LIBRARY_PATH="$HERE:$HERE/lib:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="$HERE:$HERE/lib"
fi
export LD_LIBRARY_PATH

export CHROME_VERSION_EXTRA="unstable"

# We don't want bug-buddy intercepting our crashes. http://crbug.com/24120
export GNOME_DISABLE_CRASH_DIALOG=SET_BY_GOOGLE_CHROME

# Sanitize std{in,out,err} because they'll be shared with untrusted child
# processes (http://crbug.com/376567).
exec < /dev/null
exec > >(exec cat)
exec 2> >(exec cat >&2)

###############################################################################

# Launch
## need to use the chrome's binary and not the wrapper to have zypak work correctly
## at least restart is fixed this way
exec zypak-wrapper /app/extra/chrome $CHROME_USER_FLAGS "$@"
