#!/bin/bash

_icon_path=""
while IFS= read -r -d '' _icon_path; do
 install -Dm644 "$_icon_path" ${FLATPAK_DEST}/share/icons/hicolor/${_icon_path#icons/}
done < <(find icons/ \
        -type f -and \( -name 'org.fcitx_im.fcitx5.*.png' \
        -or -name 'org.fcitx_im.fcitx5.*.svg' \) -print0)
