#!/bin/bash

# use environment var for license path instead of patching 
#   /app/extra/diamond/bin/lin64/diamond_env
export LM_LICENSE_FILE="$XDG_CONFIG_HOME"/license.dat

exec /app/extra/diamond/bin/lin64/diamond "$@"
