#!/bin/bash

# update virt-manager dependencies
flatpak run \
  --filesystem=$PWD \
  --command=flatpak-pip-generator \
  io.github.flatpak.flatpak-builder-tools \
  --requirements-file=requirements.txt \
  --output python-dependencies.json
