#!/bin/bash

# chrome's process singleton
export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID

if [[ -f $XDG_CONFIG_HOME/chrome-flags.conf ]]; then
   CHROME_USER_FLAGS="$(cat ${XDG_CONFIG_HOME}/chrome-flags.conf | egrep -v -e '^#' -e '^$')"
fi

# Launch
exec zypak-wrapper.sh /app/extra/opt/google/chrome/google-chrome $CHROME_USER_FLAGS "$@"
