#!/bin/bash

set -o errexit

CONFIG_PATH="$HOME"/.config
TOOLS_PATH="$HOME"/.config/"Mbed Studio"/mbed-studio-tools
TOOLS_SRC=/app/extra/MbedStudio/mbed-studio-tools

update_tools() {
  rm -rf "$TOOLS_PATH" "$TOOLS_PATH".tmp
  cp -r $TOOLS_SRC "$TOOLS_PATH".tmp
  mv "$TOOLS_PATH".tmp "$TOOLS_PATH"
}

if [ -f "$TOOLS_PATH"/release_version ]; then
  if diff "$TOOLS_PATH"/release_version $TOOLS_SRC/release_version; then
    :
  else
    update_tools
  fi
else
  update_tools
fi

export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID

exec /app/extra/MbedStudio/MbedStudio "$@"
