#!/bin/bash

set -o errexit

CONFIG_PATH="$HOME"/.config
TOOLS_PATH="$HOME"/.config/"Mbed Studio"/mbed-studio-tools
TOOLS_SRC=/app/extra/mbed-studio-tools

update_tools() {
  rm -rf "$TOOLS_PATH" "$TOOLS_PATH".tmp
  cp -r $TOOLS_SRC "$TOOLS_PATH".tmp
  mv "$TOOLS_PATH".tmp "$TOOLS_PATH"
}

if [ -f "$TOOLS_PATH"/.version ]; then
  if diff "$TOOLS_PATH"/.version $TOOLS_SRC/.version; then
    :
  else
    update_tools
  fi
else
  update_tools
fi

export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID

# TODO: enable the sandbox
#exec zypak-wrapper /app/extra/MbedStudio "$@"
exec /app/extra/MbedStudio --no-sandbox "$@"
