#!/bin/bash

# TODO: handle initial install and upgrades

# TODO: maybe %CSIDL_APPDATA% can be used
exec wine "C:\\users\\${USER}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Autodesk\\Autodesk Fusion 360.lnk" "$@"
