#!/bin/bash

_FPID=org.xpra.xpra

[ -f ${_FPID}.yaml ] || { echo "Can't find ${_FPID}.yaml"; exit 1; }

tools/pip-updater python-dependencies

pushd python-cryptography
../tools/pip-cargo-updater python-cryptography
../tools/pip-updater python-dependencies
popd
